id: P001714
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 10:16:13.314560
source_metadata:
  id: bdr:W1GS54860
  title: ཐུབ་དབང་གནས་བརྟན་བཅུ་དྲུག་དང་བཅས་པ་ལ་མཆོད་ཅིང་གསོལ་བ་གདབ་པའི་ཆོ་ག་ཐུབ་བསྟན་རྒྱས་བྱེད་ཡིད་བཞིན་ནོར་བུའི་སྤྱི་དངོས་རྗེས་གསུམ་དུ་ཇི་ལྟར་བྱ་བའི་ཚུལ་གསལ་བར་བཀོད་པ་དངོས་གྲུབ་ཀུན་འབྱུང
  author: ''
  volumes:
    38a1f8cd2de749498a009e119c98e69a:
      image_group_id: I1GS54862
      title: ''
      volume_number: 1
      total_pages: 82
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
